### ISSUE TITLE
error: cannot use [ -s | --select ] with [ -p ]

### ISSUE THREAD

**Issue by nerd190** [kazhala/dump-cli#2]
Thank you, this is great!
Help states that [ -s | --select ] option can be used in any situation ( -p | -u | -c ) but it only works with [ -u | -c ] options, not when adding trash with [ -p ], would be nice to select items to trash with `fzf`/`fzy`/`skim` etc.
Thanks again!

**Comment by kazhala** [comment]
Hey @5c0tt-b0t,

Thanks for the report. I just tried `dump -p -s` or `dump -s` in both `zsh` and `bash`, but could not reproduce the issue.

I'm not sure what could be the causes, could you elaborate a bit more on the command you were typing and the error message you were getting?

Cheers,
Kevin

**Comment by nerd190** [comment]
The culprit is the `-s` arg used for the `find` commands, it is first seen in line 84:
```bash
done < <(find -s . -maxdepth 1 -mindepth 1 -type d -print0 | xargs -0 -I __ basename __)

```
It produces this error:
```bash
$ dump -s
find: unknown predicate `-s'
$ dump -p -s
find: unknown predicate `-s'
```
I checked `find --help`, `man find` & many online examples too but nowhere states an `-s` option either, are you perhaps running MacOS or Windows?

I removed the `-s` args and everything works perfectly! not sure what the `-s` flag is there to achieve on your system but it isnt needed on mine.
```bash
$ find --version
find (GNU findutils) 4.8.0
```
Just an idea:
```bash
# Test if '-s' argument is available:
command -v 'find -s'
```
Perhaps used like so: (untested)
```bash
if command -v 'find -s'; then
  # exists: use '-s'
  FIND="find -s . -maxdepth 1 -mindepth 1 -type d -print0 | xargs -0 -I __ basename __"
else
  # not available: remove '-s'
  FIND="find . -maxdepth 1 -mindepth 1 -type d -print0 | xargs -0 -I __ basename __"
fi
```
Then replace the `find` commands that contain '-s' with `$FIND` instead?

Thanks again!

**Comment by kazhala** [comment]
Hi @5c0tt-b0t ,

Thanks for pointing out and you are right, I'm on MacOS and `find -s` is probably only available on BSD based system. The `-s` flag is just a sorting flag that automatically sorts the result of `find`. I've made a fix using `find | sort -z` to have the same behaviour.

I've tested on Ubuntu and its working alright now. Can you give it a try?

Cheers,
Kevin

**Comment by nerd190** [comment]
Works perfectly! thanks for that, great work! its appreciated!
